### ISSUE TITLE
hca dss upload progress bar

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/dcp-cli#396] opened 2019-07-19 20:34 UTC
As a user of the cli, when performing a `hca dss upload`  it would be helpful to see the progress of the upload as its occurring. This would allow insight to how much of a directory has been uploaded.

**Comment by natanlao** [comment] 2019-08-15 21:46
Duplicate of #117

**Closed** 2019-08-15 21:46 UTC
