### ISSUE TITLE
--no-data not working for dss download-manifest command

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/dcp-cli#445] opened 2019-09-13 20:09 UTC
I tried

`hca dss download-manifest --manifest pancreas-female.tsv --replica aws --layout bundle --no-data`

And I noticed that I was still getting fastq downloads with the console logging showing:

```
INFO:hca:File SRR3562798_2.fastq.gz: Retrieving...
INFO:hca:File SRR3562798_1.fastq.gz: Retrieving.
```

**Comment by NoopDog** [comment] 2019-09-13 20:11
[pancreas-female.tsv.zip](https://github.com/HumanCellAtlas/dcp-cli/files/3611654/pancreas-female.tsv.zip)

Adding the TSV used (zipped up)

**Comment by theathorn** [comment] 2019-09-23 17:17
Spike to determine cause.

**Comment by jessebrennan** [comment] 2019-11-13 23:37
I could not recreate this using version 6.5.0 of the CLI. @NoopDog can you confirm the version?

**Comment by theathorn** [comment] 2019-11-14 19:25
Can't reproduce - closing.
@NoopDog You may re-open with more specific evidence.

**Comment by jessebrennan** [comment] 2019-11-14 21:06
Here is my evidence:

```
(venv2) jesse@vader ~/gi/dcp-cli/test (issues/jessebrennan/445-no-data)$ hca --version
hca 6.5.0 (CPython 3.6.8 Linux-4.15.0-70-generic-x86_64-with-Ubuntu-18.04-bionic)
(venv2) jesse@vader ~/gi/dcp-cli/test (issues/jessebrennan/445-no-data)$ hca dss download-manifest --manifest ../pancreas-female.tsv --replica aws --layout bundle --no-data &>  download-6.5.0.log
(venv2) jesse@vader ~/gi/dcp-cli/test (issues/jessebrennan/445-no-data)$ fgrep fastq download-6.5.0.log
(venv2) jesse@vader ~/gi/dcp-cli/test (issues/jessebrennan/445-no-data)$ 
```

**Closed by jessebrennan** 2019-11-14 21:06 UTC
Labels: BUG, orange
